import sys
import argparse
from crm import add_lead, get_all_leads
from outreach import generate_pitch, create_gmail_draft, send_gmail_message
from calendar_helper import create_discovery_call

def process_prospect(business_name, contact_name, email, role="Founder / Owner", phone="", city="Bangalore", niche="Dental Clinic", website="", auto_send=False):
    print("\n" + "="*60)
    print(f"🎯 PROCESSING PROSPECT: {business_name} ({contact_name})")
    print("="*60)
    
    # 1. Generate customized pitch
    subject, body = generate_pitch(contact_name, business_name, niche, city)
    print(f"Generated Subject: {subject}")
    print("\n--- Pitch Preview ---")
    print(body[:220] + "...\n---------------------")
    
    # 2. Add to Google Sheets CRM
    status = "Sent" if auto_send else "Drafted in Gmail"
    add_lead(
        business_name=business_name,
        contact_name=contact_name,
        role=role,
        email=email,
        phone=phone,
        city=city,
        niche=niche,
        website=website,
        ai_hook=f"AI 24/7 Booking Assistant for {niche} in {city}",
        status=status,
        notes="Outreach generated by Antigravity Engine A"
    )
    
    # 3. Create Gmail Draft or Send
    if auto_send:
        send_gmail_message(email, subject, body)
        print(f"🚀 Email dispatched to {email}!")
    else:
        create_gmail_draft(email, subject, body)
        print(f"📝 Draft saved directly in your Gmail ({email})! Open Gmail to review and send.")

def main():
    parser = argparse.ArgumentParser(description="Engine A: B2B Client Acquisition Pipeline")
    parser.add_argument("--business", required=False, help="Business name")
    parser.add_argument("--contact", required=False, help="Contact person name")
    parser.add_argument("--email", required=False, help="Target email address")
    parser.add_argument("--role", default="Owner", help="Contact role")
    parser.add_argument("--phone", default="", help="Phone / WhatsApp")
    parser.add_argument("--city", default="Bangalore", help="City")
    parser.add_argument("--niche", default="Dental Clinic", help="Niche")
    parser.add_argument("--website", default="", help="Website")
    parser.add_argument("--send", action="store_true", help="Send immediately instead of creating draft")
    
    args = parser.parse_args()
    
    if args.business and args.contact and args.email:
        process_prospect(
            business_name=args.business,
            contact_name=args.contact,
            email=args.email,
            role=args.role,
            phone=args.phone,
            city=args.city,
            niche=args.niche,
            website=args.website,
            auto_send=args.send
        )
    else:
        print("Engine A Ready! Run with arguments or call via Python.")
        leads = get_all_leads()
        print(f"Live CRM has {len(leads)} leads recorded.")

if __name__ == '__main__':
    main()
